### ISSUE TITLE
Feature request: alphet

### ISSUE THREAD

**Issue by morristam0505** [eliranwong/letmedoit#30]
Hi,
 

Would you please consider adding an option to list menu functions in alphabetical order for easier search?

Thank you very much.

Morris

**Comment by eliranwong** [comment]
I implemented filter in the latest version which is much better than alphabetical order.  I will write a wiki page about it and post the link soon.

some screenshots first:

![action_menu_0](https://github.com/eliranwong/letmedoit/assets/25262722/5519d920-94db-4575-b66f-0f4a7549544e)

![action_menu_3](https://github.com/eliranwong/letmedoit/assets/25262722/53b71a13-ce24-4efa-85ef-cf387ede5082)

![action_menu_1](https://github.com/eliranwong/letmedoit/assets/25262722/0030aa56-8806-4ec7-b578-007202bc24ce)
![action_menu_2](https://github.com/eliranwong/letmedoit/assets/25262722/4e552377-7568-49e6-88ad-c7c6dc3a984e)

**Comment by eliranwong** [comment]
https://github.com/eliranwong/letmedoit/wiki/Action-Menu
