### ISSUE TITLE
Add Plugin: access weather information

### ISSUE THREAD

**Issue by eliranwong** [eliranwong/letmedoit#32]
Add Plugin: access weather information

**Comment by eliranwong** [comment]
api setup: https://github.com/eliranwong/letmedoit/wiki/OpenWeatherMap-API-Setup

![openweathermap_signup](https://github.com/eliranwong/letmedoit/assets/25262722/197c88e0-368b-4eef-b936-79dcae507e08)

**Comment by eliranwong** [comment]
Testing prompt:

>>> What is the current weather in New York?

![test_weather_plugin](https://github.com/eliranwong/letmedoit/assets/25262722/e9fd4376-1579-40e0-b1b2-a2b7c5583f0c)

**Comment by eliranwong** [comment]
uploaded https://github.com/eliranwong/letmedoit/commit/d5d4d4356434a9058e39036a52899470e6039486

**Comment by eliranwong** [comment]
wiki pages:

https://github.com/eliranwong/letmedoit/wiki/OpenWeatherMap-API-Setup

https://github.com/eliranwong/letmedoit/wiki/Search-Weather-Information

**Comment by mgunnin** [comment]
I'm getting this error when trying to set the API key

![CleanShot 2024-01-22 at 10 24 57](https://github.com/eliranwong/letmedoit/assets/321368/1a5afdd2-e092-4ab9-990c-ed46bb0c980e)

**Comment by eliranwong** [comment]
fixed api key setup prompt
