### ISSUE TITLE
PyAudio failed to load

### ISSUE THREAD

**Issue by mikev-db** [eliranwong/letmedoit#47]
I was getting `unable to locate a Java Rntime that supports apt` while it was trying to load PyAudio. 

To fix this, I did: 

```
source letmedoit/bin/activate
brew install portaudio
pip install pyaudio
```

After that, letmedoit loaded normally.

Just letting you know in case you think this might be more common than just my environment (MacOS, M1, Sonoma 14.3.1)

**Comment by eliranwong** [comment]
Thanks for your information, I should add this to the wiki pages.  So, have the issues been sorted on your side?

**Comment by mikev-db** [comment]
Yes, this sorted it out.

**Comment by eliranwong** [comment]
I added your a link to your fix at https://github.com/eliranwong/letmedoit/wiki/Speak-to-LetMeDoIt-AI

Many thanks.
