### ISSUE TITLE
Privacy Concern

### ISSUE THREAD

**Issue by thelege2nd** [eliranwong/letmedoit#53]
Do you collect any data or telemetry?

**Comment by eliranwong** [comment]
NO, definitely NO!  I don't collect any.  I am aware of Chromadb collect telemetry by default.  I deliberately turned that off in my project.

So, in short, NO, I myself don't collect any data or telemetry.  Please feel free to check the source code.  All are transparent.

With that said, if you use ChatGPT, your entered queries are uploaded to OpenAI.  Some commercial users have concerns and requested my project to support totally free, local and offline open-source LLMs.  If you have the same concerns about OpenAI, the following project, still baking, is the answer:

https://github.com/eliranwong/freegenius

**Comment by thelege2nd** [comment]
Thanks for the swift answer! I will check the source code later.

Is there a difference or an advantage between this project and Open Interpreter/Rawdog?

**Comment by eliranwong** [comment]
I appreciate other people work. I prefer to let other LetMeDoIt users to tell the difference. I myself have already uninstalled open-interpreter for few months ago, as it cannot meet my needs.  So, I am not right person to comment further.
