### ISSUE TITLE
Changing base url

### ISSUE THREAD

**Issue by thelege2nd** [eliranwong/letmedoit#54]
I have not installed it yet, but I didn't see any documentation on how to change the API base URL?

I want to send the requests to my localhost:PORT as that's where I am running a self hosted API for GPT 4.

**Comment by eliranwong** [comment]
At the moment, this option is not supported.

**Comment by thelege2nd** [comment]
but since letmedoit can be used with local models, then it should be able easy to change the API endpoint for openai too.

**Comment by eliranwong** [comment]
It makes sense, I will implement it in https://github.com/eliranwong/freegenius

Alternately, welcome a pull request to letmedoit

**Comment by fvkd** [comment]
Ok, so this can't use Google Gemini or Ollama? Because it states in the README that this supports localy hosted llms and various models like Google Gemini. I'm not understands why you MUST have an OpenAI api to use Gemini with this. Would someone be awesome and explain please?

**Comment by eliranwong** [comment]
For using with open-source LLMs, please check: https://github.com/eliranwong/freegenius
