### ISSUE TITLE
Question about rebuilding missing chromasqlite3 database

### ISSUE THREAD

**Issue by Orion120** [eliranwong/letmedoit#57]
I've been having issues with autogen, and noticed that the chromasqlite3 db was missing from the folder. Both Chat and Memory have their dbs. What is the best way to remedy this? Do I need to change embedding model to have it refresh?

**Comment by eliranwong** [comment]
what errors do you get from the terminal?

**Comment by Orion120** [comment]
This has been popping up on crash or attempts to save recently:


```    raise RuntimeError(
RuntimeError: Failed to import transformers.models.xlm_roberta.modeling_xlm_roberta because of the following error (look up to see its traceback):
Failed to import transformers.generation.utils because of the following error (look up to see its traceback):
module 'lib' has no attribute 'X509_V_FLAG_NOTIFY_POLICY'
```

**Comment by eliranwong** [comment]
Hi @Orion120 have you sorted this issued?
