### ISSUE TITLE
"Error: Issue on OpenAI side"

### ISSUE THREAD

**Issue by hrungue** [eliranwong/letmedoit#59]
![image](https://github.com/eliranwong/letmedoit/assets/94649875/aa16105d-4910-4363-aae1-68aeb7f5a71f)

**Comment by hrungue** [comment]
im entering the key copy and paste it but is not working please i need help

**Comment by eliranwong** [comment]
Hi, thanks for your message.

I have just tried a fresh installation.  I entered the api key and it works as expected.

Please make sure you enter a valid api key.  Recently, openai migrated billing method to prepaid.  API key may work only if billing is set up and credits are purchased.

You may also try to close the app first.  Edit config.py manually to enter the value of your api key as the value of of item "openaiApiKey",
